on: 
  push:
    branches: main

name: 🚀 Deploy Estou On push Back
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.2
      with:
        server: ${{ secrets.ftp_host }}
        username: ${{ secrets.ftp_user }}
        password: ${{ secrets.ftp_password }}
        server-dir: estouon.app.br-dev/back
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/.htaccess
          **/_includes/config.php
 